In [315]:
import pandas as pd
import numpy as np

- understanding data

In [316]:
df=pd.read_csv('indian-movies.csv')

In [360]:
df.sample(1)

,movie_id,overview,title,genres,keywords,cast,crew,tags
268,102632,"[A, small-time, thug, comes, across, a, young,...",Rowdy Rathore,"[Action, Comedy, Crime]","[fight, cop, love, remake, thief, revenge, loo...","[AkshayKumar, SonakshiSinha, Nassar, YashpalSh...",[PrabhuDeva],"[A, small-time, thug, comes, across, a, young,..."

In [318]:
df.columns

Index(['movie_id', 'original_language', 'original_title', 'overview',
       'popularity', 'release_date', 'title', 'video', 'vote_average',
       'vote_count', 'genres', 'keywords', 'cast', 'crew', 'month', 'year'],
      dtype='object')

- taking useful features

In [319]:
df=df[['movie_id', 'overview', 'title',
        'genres', 'keywords', 'cast', 'crew']]

In [320]:
df.shape

(3099, 7)

In [321]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3099 entries, 0 to 3098
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  3099 non-null   int64
 1   overview  3051 non-null   object
 2   title     3098 non-null   object
 3   genres    3098 non-null   object
 4   keywords  3098 non-null   object
 5   cast      3098 non-null   object
 6   crew      3098 non-null   object
dtypes: int64(1), object(6)
memory usage: 169.6+ KB

- dropping null values

In [322]:
df.isnull().sum()

movie_id     0
overview    48
title        1
genres       1
keywords     1
cast         1
crew         1
dtype: int64

In [323]:
df=df.dropna()

- converting string of list to list

In [324]:
import ast

- getting genres in a list

In [325]:
def get_name(x):
    l=[]
    for i in ast.literal_eval(x):
        l.append(i['name'])
    return l

In [326]:
df['genres']=df['genres'].apply(get_name)

In [327]:
df['genres'][0]

['Action', 'Comedy', 'Crime']

- converting keyword into a list of strings

In [328]:
df['keywords'][1]

"['police', 'sequel', 'police officer', 'cop universe']"

In [329]:
def convert(obj):
    l=[]
    for i in ast.literal_eval(obj):
        l.append(i)
    return l

In [330]:
df['keywords']=df['keywords'].apply(convert)

- getting top 4 cast

In [331]:
df['cast'][0]

"[{'adult': False, 'gender': 1, 'id': 550167, 'known_for_department': 'Acting', 'name': 'Taapsee Pannu', 'original_name': 'Taapsee Pannu', 'popularity': 6.156, 'profile_path': '/u9Gwg3J0bdczTPunP8qoWK2Vhu4.jpg', 'cast_id': 1, 'character': 'Savi', 'credit_id': '5ff5b30128723c0040af9605', 'order': 0}, {'adult': False, 'gender': 2, 'id': 1714229, 'known_for_department': 'Acting', 'name': 'Tahir Raj Bhasin', 'original_name': 'Tahir Raj Bhasin', 'popularity': 2.203, 'profile_path': '/A4ylMYWj8IqnmX74Two8c4Lp8jY.jpg', 'cast_id': 3, 'character': 'Satya', 'credit_id': '5ff5b31dd38b580043cb4047', 'order': 1}, {'adult': False, 'gender': 1, 'id': 2092738, 'known_for_department': 'Acting', 'name': 'Shreya Dhanwanthary', 'original_name': 'Shreya Dhanwanthary', 'popularity': 8.802, 'profile_path': '/dSWHYuEWjPzczAzdLFgYHt3Y5Dd.jpg', 'cast_id': 15, 'character': 'Julia', 'credit_id': '6136133e2cde980089dc0082', 'order': 2}, {'adult': False, 'gender': 2, 'id': 101823, 'known_for_department': 'Acting', 'name': 'Dibyendu Bhattacharya', 'original_name': 'Dibyendu Bhattacharya', 'popularity': 6.209, 'profile_path': '/uLlGKCL9y5CFBwcAafTDQhupz5h.jpg', 'cast_id': 22, 'character': 'Victor', 'credit_id': '61d91fac33a53300415c3d18', 'order': 3}, {'adult': False, 'gender': 0, 'id': 1252843, 'known_for_department': 'Acting', 'name': 'Rajendra Chawla', 'original_name': 'Rajendra Chawla', 'popularity': 1.108, 'profile_path': '/rwldmP0tneEflAVgOaQsYmvTZju.jpg', 'cast_id': 21, 'character': 'Mamlesh Charan Chaddha', 'credit_id': '61d91fa2a6fdaa009333e436', 'order': 4}, {'adult': False, 'gender': 2, 'id': 2365591, 'known_for_department': 'Acting', 'name': 'K.C. Shankar', 'original_name': 'K.C. Shankar', 'popularity': 2.075, 'profile_path': '/fbxJMM6YZGl3OLHhnqISzPjbSpB.jpg', 'cast_id': 23, 'character': 'Atul Borkar', 'credit_id': '61d91fb833a53300415c3d36', 'order': 5}, {'adult': False, 'gender': 2, 'id': 1927085, 'known_for_department': 'Directing', 'name': 'Suresh Triveni', 'original_name': 'Suresh Triveni', 'popularity': 0.98, 'profile_path': None, 'cast_id': 34, 'character': 'Gangster Pedro', 'credit_id': '61e2f1d4ffd44d006bd2b773', 'order': 6}, {'adult': False, 'gender': 2, 'id': 2967857, 'known_for_department': 'Acting', 'name': 'Manik Papneja', 'original_name': 'Manik Papneja', 'popularity': 1.177, 'profile_path': '/bjVqyExEk5n1qHLuOnbR8UbPLpY.jpg', 'cast_id': 24, 'character': 'Appu', 'credit_id': '61d91fc9293835009569944f', 'order': 7}, {'adult': False, 'gender': 2, 'id': 2400790, 'known_for_department': 'Acting', 'name': 'Raghav Raj Kakker', 'original_name': 'Raghav Raj Kakker', 'popularity': 1.22, 'profile_path': '/p4TqLqcbyZWryGGDJjMaYL89CfU.jpg', 'cast_id': 25, 'character': 'Gappu', 'credit_id': '61d91fe09824c8004140a205', 'order': 8}, {'adult': False, 'gender': 2, 'id': 1951414, 'known_for_department': 'Acting', 'name': 'Sameer Kevin Roy', 'original_name': 'Sameer Kevin Roy', 'popularity': 1.38, 'profile_path': None, 'cast_id': 26, 'character': 'Jacob', 'credit_id': '61d91fea5ed8e9001d41c9e2', 'order': 9}, {'adult': False, 'gender': 2, 'id': 3373394, 'known_for_department': 'Acting', 'name': 'Bhupesh Bandekar', 'original_name': 'Bhupesh Bandekar', 'popularity': 0.98, 'profile_path': None, 'cast_id': 27, 'character': 'Inspector David Colaco', 'credit_id': '61d91ff70e5aba0042ffb116', 'order': 10}, {'adult': False, 'gender': 2, 'id': 3412117, 'known_for_department': 'Acting', 'name': 'Alistar Bennis', 'original_name': 'Alistar Bennis', 'popularity': 0.98, 'profile_path': None, 'cast_id': 49, 'character': 'Robert', 'credit_id': '61fce7ee1e259a0113e2778e', 'order': 11}, {'adult': False, 'gender': 2, 'id': 3412118, 'known_for_department': 'Acting', 'name': 'Varun Pande', 'original_name': 'Varun Pande', 'popularity': 0.6, 'profile_path': None, 'cast_id': 50, 'character': 'Yash', 'credit_id': '61fce7fadfaae9009c588c3f', 'order': 12}, {'adult': False, 'gender': 0, 'id': 3412128, 'known_for_department': 'Acting', 'name': 'Babajaan Devaraya', 'original_name': 'Babajaan Devaraya', 'popularity': 0.6, 'profile_path': None, 'cast_id': 60, 'character': 'Rastafarian', 'credit_id': '61fcea25eee18600cd3e95d0', 'order': 13}, {'adult': False, 'gender': 0, 'id': 3412129, 'known_for_department': 'Acting', 'name': 'Guia Bianchi', 'original_name': 'Guia Bianchi', 'popularity': 0.6, 'profile_path': None, 'cast_id': 61, 'character': 'Lola', 'credit_id': '61fcea3d7a97ab00732bb9e9', 'order': 14}, {'adult': False, 'gender': 1, 'id': 3565643, 'known_for_department': 'Acting', 'name': 'Priya Paramita Paul', 'original_name': 'Priya Paramita Paul', 'popularity': 0.6, 'profile_path': '/zTRyZGrYPMEWXXCw2NBGzupvAqL.jpg', 'cast_id': 62, 'character': 'zoya', 'credit_id': '62906bf3a24232009b59114b', 'order': 15}]"

In [332]:
def cast_convert(x):
    l=[]
    ct=0
    for i in ast.literal_eval(x):
        if ct!=4:
            l.append(i['name'])
            ct+=1
        else:
            break
    return l

In [333]:
df['cast']=df['cast'].apply(cast_convert)

- gettiing director from crew

In [334]:
df['crew'][0]

"[{'adult': False, 'gender': 2, 'id': 1071, 'known_for_department': 'Directing', 'name': 'Tom Tykwer', 'original_name': 'Tom Tykwer', 'popularity': 4.312, 'profile_path': '/cu7F4AulzRbj0dZH9s5pRM61w64.jpg', 'credit_id': '617796df9ee0ef008c45483e', 'department': 'Writing', 'job': 'Original Story'}, {'adult': False, 'gender': 2, 'id': 1108802, 'known_for_department': 'Production', 'name': 'Mukesh Chhabra', 'original_name': 'Mukesh Chhabra', 'popularity': 2.972, 'profile_path': '/f5XI2wJs2JPcd5FSECsdcnkyOMW.jpg', 'credit_id': '61e09db05bce9e0041751368', 'department': 'Production', 'job': 'Casting Director'}, {'adult': False, 'gender': 0, 'id': 1208683, 'known_for_department': 'Production', 'name': 'Tanuj Garg', 'original_name': 'Tanuj Garg', 'popularity': 0.6, 'profile_path': None, 'credit_id': '5ff5b40d245dbe003d301373', 'department': 'Production', 'job': 'Producer'}, {'adult': False, 'gender': 0, 'id': 1376941, 'known_for_department': 'Production', 'name': 'Siddharth Atha', 'original_name': 'Siddharth Atha', 'popularity': 0.6, 'profile_path': None, 'credit_id': '61fce8f26f31af008f869555', 'department': 'Production', 'job': 'Executive Producer'}, {'adult': False, 'gender': 2, 'id': 1434492, 'known_for_department': 'Crew', 'name': 'Ejaz Gulab', 'original_name': 'Ejaz Gulab', 'popularity': 0.98, 'profile_path': None, 'credit_id': '61fce8915c3247009504c450', 'department': 'Crew', 'job': 'Stunt Coordinator'}, {'adult': False, 'gender': 0, 'id': 1561318, 'known_for_department': 'Production', 'name': 'Atul Kasbekar', 'original_name': 'Atul Kasbekar', 'popularity': 0.6, 'profile_path': None, 'credit_id': '5ff5b4267e9d5f004032ac2b', 'department': 'Production', 'job': 'Producer'}, {'adult': False, 'gender': 0, 'id': 1561320, 'known_for_department': 'Production', 'name': 'Shanti Sivaram Maini', 'original_name': 'Shanti Sivaram Maini', 'popularity': 0.6, 'profile_path': None, 'credit_id': '61fce92364de35004421dedd', 'department': 'Production', 'job': 'Co-Producer'}, {'adult': False, 'gender': 0, 'id': 1682059, 'known_for_department': 'Art', 'name': 'Aashish Porwal', 'original_name': 'Aashish Porwal', 'popularity': 0.6, 'profile_path': None, 'credit_id': '5ff5b46ab865eb003cb1ef68', 'department': 'Art', 'job': 'Art Direction'}, {'adult': False, 'gender': 0, 'id': 1730578, 'known_for_department': 'Lighting', 'name': 'Yash Khanna', 'original_name': 'Yash Khanna', 'popularity': 0.6, 'profile_path': None, 'credit_id': '6177964fa579f90027164d8c', 'department': 'Camera', 'job': 'Director of Photography'}, {'adult': False, 'gender': 0, 'id': 1860546, 'known_for_department': 'Production', 'name': 'Simran Sawhney', 'original_name': 'Simran Sawhney', 'popularity': 0.6, 'profile_path': None, 'credit_id': '5ff5b44cd38b580041cbc125', 'department': 'Production', 'job': 'Producer'}, {'adult': False, 'gender': 0, 'id': 1985232, 'known_for_department': 'Sound', 'name': 'Gautam Nair', 'original_name': 'Gautam Nair', 'popularity': 0.6, 'profile_path': None, 'credit_id': '61fce869ce997a010f725729', 'department': 'Sound', 'job': 'Sound Designer'}, {'adult': False, 'gender': 0, 'id': 2035070, 'known_for_department': 'Costume & Make-Up', 'name': 'Indrakshi Pattanaik', 'original_name': 'Indrakshi Pattanaik', 'popularity': 0.6, 'profile_path': None, 'credit_id': '61e08aa31511aa001c122ad5', 'department': 'Costume & Make-Up', 'job': 'Costume Designer'}, {'adult': False, 'gender': 0, 'id': 2036033, 'known_for_department': 'Editing', 'name': 'Priyank Prem Kumar', 'original_name': 'Priyank Prem Kumar', 'popularity': 0.6, 'profile_path': None, 'credit_id': '617797016e0d720063599cec', 'department': 'Editing', 'job': 'Editor'}, {'adult': False, 'gender': 0, 'id': 2266291, 'known_for_department': 'Art', 'name': 'Pradeep Paul Francis', 'original_name': 'Pradeep Paul Francis', 'popularity': 0.6, 'profile_path': None, 'credit_id': '61fce8b05c324700ddac68aa', 'department': 'Art', 'job': 'Production Design'}, {'adult': False, 'gender': 0, 'id': 2266293, 'known_for_department': 'Art', 'name': 'Diya Mukerjea', 'original_name': 'Diya Mukerjea', 'popularity': 0.6, 'profile_path': None, 'credit_id': '61fce8c56f31af00ba036b8b', 'department': 'Art', 'job': 'Production Design'}, {'adult': False, 'gender': 0, 'id': 2329287, 'known_for_department': 'Writing', 'name': 'Vinay Chhawal', 'original_name': 'Vinay Chhawal', 'popularity': 0.98, 'profile_path': None, 'credit_id': '61d9201f6331b200990b4acb', 'department': 'Writing', 'job': 'Writer'}, {'adult': False, 'gender': 0, 'id': 2542498, 'known_for_department': 'Production', 'name': 'Aakash Bhatia', 'original_name': 'Aakash Bhatia', 'popularity': 1.38, 'profile_path': None, 'credit_id': '617797a8894ed60064768a3b', 'department': 'Directing', 'job': 'Director'}, {'adult': False, 'gender': 0, 'id': 2542498, 'known_for_department': 'Production', 'name': 'Aakash Bhatia', 'original_name': 'Aakash Bhatia', 'popularity': 1.38, 'profile_path': None, 'credit_id': '61d920446dea3a001f020890', 'department': 'Writing', 'job': 'Writer'}, {'adult': False, 'gender': 0, 'id': 2553014, 'known_for_department': 'Sound', 'name': 'Sharvi Yadav', 'original_name': 'Sharvi Yadav', 'popularity': 0.6, 'profile_path': None, 'credit_id': '61e6904ac613ce008cefbfe5', 'department': 'Sound', 'job': 'Playback Singer'}, {'adult': False, 'gender': 0, 'id': 2680859, 'known_for_department': 'Writing', 'name': 'Puneet Chadha', 'original_name': 'Puneet Chadha', 'popularity': 0.6, 'profile_path': None, 'credit_id': '61fce90d64de35004421ded5', 'department': 'Crew', 'job': 'Additional Dialogue'}, {'adult': False, 'gender': 0, 'id': 2783444, 'known_for_department': 'Writing', 'name': 'Siddhant Kaushal', 'original_name': 'Siddhant Kaushal', 'popularity': 0.6, 'profile_path': None, 'credit_id': '61e690617d2bc1009fd31847', 'department': 'Writing', 'job': 'Lyricist'}, {'adult': False, 'gender': 0, 'id': 2925506, 'known_for_department': 'Production', 'name': 'Aayush Maheshwari', 'original_name': 'Aayush Maheshwari', 'popularity': 0.6, 'profile_path': None, 'credit_id': '5ff5b43a7e9d5f003e325971', 'department': 'Production', 'job': 'Producer'}, {'adult': False, 'gender': 0, 'id': 2925509, 'known_for_department': 'Production', 'name': 'Rohit Chandaliya', 'original_name': 'Rohit Chandaliya', 'popularity': 0.6, 'profile_path': None, 'credit_id': '5ff5b4b0f48e0d004172b353', 'department': 'Production', 'job': 'Production Manager'}, {'adult': False, 'gender': 0, 'id': 3139446, 'known_for_department': 'Writing', 'name': 'Sidhant Mago', 'original_name': 'Sidhant Mago', 'popularity': 0.98, 'profile_path': None, 'credit_id': '61e68f84a402c1001c119804', 'department': 'Sound', 'job': 'Original Music Composer'}, {'adult': False, 'gender': 0, 'id': 3139446, 'known_for_department': 'Writing', 'name': 'Sidhant Mago', 'original_name': 'Sidhant Mago', 'popularity': 0.98, 'profile_path': None, 'credit_id': '61e68f8e2d93750066f4b059', 'department': 'Sound', 'job': 'Playback Singer'}, {'adult': False, 'gender': 0, 'id': 3139446, 'known_for_department': 'Writing', 'name': 'Sidhant Mago', 'original_name': 'Sidhant Mago', 'popularity': 0.98, 'profile_path': None, 'credit_id': '61e68fa2a402c10042e9419c', 'department': 'Writing', 'job': 'Lyricist'}, {'adult': False, 'gender': 0, 'id': 3220399, 'known_for_department': 'Production', 'name': 'Vivek Krishnani', 'original_name': 'Vivek Krishnani', 'popularity': 0.6, 'profile_path': None, 'credit_id': '61d91f885ed8e9001d41c8bf', 'department': 'Production', 'job': 'Producer'}, {'adult': False, 'gender': 0, 'id': 3340143, 'known_for_department': 'Sound', 'name': 'Ronkini Gupta', 'original_name': 'Ronkini Gupta', 'popularity': 0.6, 'profile_path': None, 'credit_id': '61e53cff0cd32a0042fa6941', 'department': 'Sound', 'job': 'Playback Singer'}, {'adult': False, 'gender': 0, 'id': 3357290, 'known_for_department': 'Acting', 'name': 'Santanu Ghatak', 'original_name': 'Santanu Ghatak', 'popularity': 0.98, 'profile_path': None, 'credit_id': '61e53cdd7d2bc10041e8919a', 'department': 'Sound', 'job': 'Original Music Composer'}, {'adult': False, 'gender': 0, 'id': 3357290, 'known_for_department': 'Acting', 'name': 'Santanu Ghatak', 'original_name': 'Santanu Ghatak', 'popularity': 0.98, 'profile_path': None, 'credit_id': '61e53ceb2d93750041a5bbca', 'department': 'Writing', 'job': 'Lyricist'}, {'adult': False, 'gender': 0, 'id': 3373395, 'known_for_department': 'Writing', 'name': 'Ketan Pedgaonkar', 'original_name': 'Ketan Pedgaonkar', 'popularity': 0.98, 'profile_path': None, 'credit_id': '61d920363faba00041f7b438', 'department': 'Writing', 'job': 'Writer'}, {'adult': False, 'gender': 0, 'id': 3373396, 'known_for_department': 'Writing', 'name': 'Arnav Vepa Nanduri', 'original_name': 'Arnav Vepa Nanduri', 'popularity': 0.98, 'profile_path': None, 'credit_id': '61d9206097fdec0041035a24', 'department': 'Writing', 'job': 'Writer'}, {'adult': False, 'gender': 0, 'id': 3386264, 'known_for_department': 'Sound', 'name': 'Raghav Kaushik', 'original_name': 'Raghav Kaushik', 'popularity': 0.6, 'profile_path': None, 'credit_id': '61e53d0b6aa8e0008cc281c5', 'department': 'Sound', 'job': 'Playback Singer'}, {'adult': False, 'gender': 0, 'id': 3387728, 'known_for_department': 'Sound', 'name': 'Mayank Mehra', 'original_name': 'Mayank Mehra', 'popularity': 0.6, 'profile_path': None, 'credit_id': '61e68f746840cc0067eba773', 'department': 'Sound', 'job': 'Original Music Composer'}, {'adult': False, 'gender': 0, 'id': 3387729, 'known_for_department': 'Sound', 'name': 'Jay Anand', 'original_name': 'Jay Anand', 'popularity': 0.6, 'profile_path': None, 'credit_id': '61e68fb9f3b49a001c026418', 'department': 'Sound', 'job': 'Playback Singer'}, {'adult': False, 'gender': 0, 'id': 3387731, 'known_for_department': 'Sound', 'name': 'Harshal Vyas', 'original_name': 'Harshal Vyas', 'popularity': 0.98, 'profile_path': None, 'credit_id': '61e6900b07a8080067841de4', 'department': 'Sound', 'job': 'Playback Singer'}, {'adult': False, 'gender': 0, 'id': 3387732, 'known_for_department': 'Sound', 'name': 'Rahul Pais', 'original_name': 'Rahul Pais', 'popularity': 0.6, 'profile_path': None, 'credit_id': '61e69029b7abb50041006b2a', 'department': 'Sound', 'job': 'Original Music Composer'}, {'adult': False, 'gender': 0, 'id': 3387733, 'known_for_department': 'Sound', 'name': 'Nariman Khambata', 'original_name': 'Nariman Khambata', 'popularity': 0.6, 'profile_path': None, 'credit_id': '61e690362d93750041a91342', 'department': 'Sound', 'job': 'Original Music Composer'}, {'adult': False, 'gender': 0, 'id': 3412122, 'known_for_department': 'Production', 'name': 'Swati Iyer Chawla', 'original_name': 'Swati Iyer Chawla', 'popularity': 0.6, 'profile_path': None, 'credit_id': '61fce937ce997a006bbfd0f3', 'department': 'Production', 'job': 'Co-Producer'}, {'adult': False, 'gender': 0, 'id': 3412123, 'known_for_department': 'Production', 'name': 'Piya Sawhney', 'original_name': 'Piya Sawhney', 'popularity': 0.6, 'profile_path': None, 'credit_id': '61fce955bf0f6300a2e985ec', 'department': 'Production', 'job': 'Co-Producer'}, {'adult': False, 'gender': 0, 'id': 3865885, 'known_for_department': 'Sound', 'name': 'Shahbad Karan', 'original_name': 'Shahbad Karan', 'popularity': 0.6, 'profile_path': '/cBPJ5o4rTfe5IMuDbLty8BpXX1k.jpg', 'credit_id': '63f0ca37a6725400a3a2783a', 'department': 'Sound', 'job': 'Musician'}]"

In [335]:
def fetch_director(x):
    l=[]
    for i in ast.literal_eval(x):
        if i['job']=='Director':
            l.append(i['name'])
            break
    return l

In [336]:
df['crew']=df['crew'].apply(fetch_director)

- removing spaces from genres,keyword,cast and crew

In [337]:
df['genres']=df['genres'].apply(lambda x:[i.replace(" ","") for i in x])
df['keywords']=df['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
df['cast']=df['cast'].apply(lambda x:[i.replace(" ","") for i in x])
df['crew']=df['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [338]:
# converting overview into list of strings
df['overview']=df['overview'].apply(lambda x:x.split())

- creating a new column named tags

In [339]:
df['tags']=df['overview']+df['genres']+df['keywords']+df['cast']+df['crew']

- creating a new dataset

In [340]:
new_df=df[['movie_id','title','tags']]

In [341]:
new_df.sample()

,movie_id,title,tags
2067,343983,Aadmi Khilona Hai,"[The, Verma, family, consists, of, two, brothe..."

In [342]:
new_df=new_df.reset_index()

- converting tags into a single para in lower case

In [343]:
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

In [344]:
new_df['tags'][0]

"when her boyfriend loses a mobster's cash, savi races against the clock to save the day — if only she can break out of a curious cycle of dead ends. action comedy crime remake loooplapeta saadesaati taapseepannu tahirrajbhasin shreyadhanwanthary dibyendubhattacharya aakashbhatia"

- cleaning tags with cleantext library

In [345]:
import cleantext

In [346]:
# clean the text
def clean_text(data):
    cleaned_text=cleantext.clean(
        data,
        extra_spaces=True, #remove extra spaces
        stemming=False, #apply stremming(ex:"running" to "run")
        stopwords=True, #remove stopwords(is,a,the)
        lowercase=True, #convert text to lowercase
        numbers=True, #remove all digits
        punct=True #remove all punctuation
    )
    return cleaned_text

In [347]:
new_df['tags']=new_df['tags'].apply(clean_text)

In [348]:
new_df.iloc[0]['tags']

'boyfriend loses mobsters cash savi races clock save day — break curious cycle dead ends action comedy crime remake loooplapeta saadesaati taapseepannu tahirrajbhasin shreyadhanwanthary dibyendubhattacharya aakashbhatia'

- converting words to base word(ex:running to run)

In [349]:
import nltk
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\shiva\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\shiva\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [350]:
from nltk.stem import WordNetLemmatizer
lemmetizer=WordNetLemmatizer()

In [351]:
def stem(text):
    l=[]
    for i in text.split():
        l.append(lemmetizer.lemmatize(i,pos='v'))
    return " ".join(l)

In [352]:
new_df['tags']=new_df['tags'].apply(stem)

In [353]:
new_df.iloc[0]['tags']

'boyfriend lose mobsters cash savi race clock save day — break curious cycle dead end action comedy crime remake loooplapeta saadesaati taapseepannu tahirrajbhasin shreyadhanwanthary dibyendubhattacharya aakashbhatia'

-  converting words to array of vector

In [354]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(stop_words='english',max_features=5000)

In [355]:
vectors=cv.fit_transform(new_df['tags']).toarray()

In [356]:
cv.get_feature_names_out()

array(['aahanakumra', 'aakash', 'aalam', ..., 'zombie', 'zoya',
       'zoyaakhtar'], shape=(5000,), dtype=object)

- getting cosine similarity between vectors rowwise

In [357]:
from sklearn.metrics.pairwise import cosine_similarity
similarity=cosine_similarity(vectors)

In [358]:
similarity.shape

(3050, 3050)

- sample recommendor system

In [361]:
user_input=input("search movie:")
try:
    movie_index=new_df[new_df['title'].str.lower()==user_input.lower()].index[0]
    distances=similarity[movie_index]
    # sorting distances according to distance
    movie_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:10]
    # print(movie_list)
    print(f"------------movies similar to {user_input}-----------------")
    for i in movie_list:
        print(new_df.iloc[i[0]].title)
except Exception as e:
    print('Error:',e)

------------movies similar to Rowdy Rathore-----------------
Action Jackson
Humshakals
Agneepath
Gumraah
Dabangg 3
Mr. & Mrs. Khiladi
Once Upon a Time in Mumbai Dobaara!
Jayantabhai Ki Luv Story
Mujhe Kucch Kehna Hai

In [363]:
import pickle
with open('similarities.pkl','wb') as file:
    pickle.dump(similarity,file)
new_df.to_csv('new_df.csv')

In [365]:
import pandas as pd
import requests
import time

API_KEY = "d2d8d0cf1f7b4657743e5cb7c574ca6d"

df = pd.read_csv("new_df.csv")

def fetch_details(movie_id):
    url = f"https://api.themoviedb.org/3/movie/{movie_id}?api_key={API_KEY}"
    r = requests.get(url)

    if r.status_code != 200:
        return None, None, None

    data = r.json()

    poster = None
    if data.get("poster_path"):
        poster = "https://image.tmdb.org/t/p/w342" + data["poster_path"]

    overview = data.get("overview")
    release = data.get("release_date")

    return poster, overview, release


# create empty columns
df["poster"] = None
df["overview"] = None
df["release"] = None

for i, row in df.iterrows():
    print(f"Fetching {i+1}/{len(df)} : {row['title']}")

    poster, overview, release = fetch_details(row["movie_id"])

    df.at[i, "poster"] = poster
    df.at[i, "overview"] = overview
    df.at[i, "release"] = release

    time.sleep(0.25)  # prevent hitting rate limit

# save new file
df.to_csv("new_df_enriched.csv", index=False)

print("✅ Done. Saved as new_df_enriched.csv")

Fetching 1/3050 : Looop Lapeta
Fetching 2/3050 : Sooryavanshi
Fetching 3/3050 : Pathaan
Fetching 4/3050 : Chor Nikal Ke Bhaga
Fetching 5/3050 : 3 Idiots
Fetching 6/3050 : My Name Is Khan
Fetching 7/3050 : Dilwale Dulhania Le Jayenge
Fetching 8/3050 : Dhamaka
Fetching 9/3050 : Brahmāstra Part One: Shiva
Fetching 10/3050 : Andhadhun
Fetching 11/3050 : Om Shanti Om
Fetching 12/3050 : Blood Money
Fetching 13/3050 : Kabhi Khushi Kabhie Gham
Fetching 14/3050 : Dhoom 3
Fetching 15/3050 : Gumraah
Fetching 16/3050 : Dangal
Fetching 17/3050 : Kites
Fetching 18/3050 : Commando 2 -  The Black Money Trail
Fetching 19/3050 : Kabhi Alvida Naa Kehna
Fetching 20/3050 : Like Stars on Earth
Fetching 21/3050 : Drive
Fetching 22/3050 : Kuch Kuch Hota Hai
Fetching 23/3050 : Bodyguard
Fetching 24/3050 : Junglee
Fetching 25/3050 : The Girl on the Train
Fetching 26/3050 : Baaghi
Fetching 27/3050 : Student of the Year
Fetching 28/3050 : Karan Arjun
Fetching 29/3050 : Gangs of Wasseypur - Part 1
Fetching 30/3050 : Raees
Fetching 31/3050 : Bajrangi Bhaijaan
Fetching 32/3050 : PK
Fetching 33/3050 : Rab Ne Bana Di Jodi
Fetching 34/3050 : Dhoom 2
Fetching 35/3050 : Padmaavat
Fetching 36/3050 : Mohabbatein
Fetching 37/3050 : Mujhse Dosti Karoge!
Fetching 38/3050 : Monica, O My Darling
Fetching 39/3050 : Veer-Zaara
Fetching 40/3050 : Bang Bang!
Fetching 41/3050 : Lagaan: Once Upon a Time in India
Fetching 42/3050 : The Lunchbox
Fetching 43/3050 : Gangubai Kathiawadi
Fetching 44/3050 : Monsoon Wedding
Fetching 45/3050 : Zindagi Na Milegi Dobara
Fetching 46/3050 : Swades
Fetching 47/3050 : Dilwale
Fetching 48/3050 : Ghajini
Fetching 49/3050 : Bhaag Milkha Bhaag
Fetching 50/3050 : Jab Tak Hai Jaan
Fetching 51/3050 : Jersey
Fetching 52/3050 : Gol Maal
Fetching 53/3050 : Devdas
Fetching 54/3050 : Ludo
Fetching 55/3050 : Gaslight
Fetching 56/3050 : Ek Tha Tiger
Fetching 57/3050 : Chak De! India
Fetching 58/3050 : English Vinglish
Fetching 59/3050 : War
Fetching 60/3050 : Bholaa
Fetching 61/3050 : Vivah
Fetching 62/3050 : Gully Boy
Fetching 63/3050 : Kal Ho Naa Ho
Fetching 64/3050 : Dear Zindagi
Fetching 65/3050 : Aśoka
Fetching 66/3050 : Singham
Fetching 67/3050 : Welcome
Fetching 68/3050 : Fanaa
Fetching 69/3050 : Main Hoon Na
Fetching 70/3050 : Sholay
Fetching 71/3050 : Guilty
Fetching 72/3050 : Black
Fetching 73/3050 : Dhoom
Fetching 74/3050 : Kesari
Fetching 75/3050 : Happy New Year
Fetching 76/3050 : Sanam Teri Kasam
Fetching 77/3050 : Sultan
Fetching 78/3050 : Piku
Fetching 79/3050 : Krrish 3
Fetching 80/3050 : Tumbbad
Fetching 81/3050 : Zero
Fetching 82/3050 : Black Friday
Fetching 83/3050 : Don
Fetching 84/3050 : Jab We Met
Fetching 85/3050 : Aladin
Fetching 86/3050 : Jaadugar
Fetching 87/3050 : Kaho Naa... Pyaar Hai
Fetching 88/3050 : B.A. Pass
Fetching 89/3050 : OMG: Oh My God!
Fetching 90/3050 : Bajirao Mastani
Fetching 91/3050 : Drishyam
Fetching 92/3050 : Baazigar
Fetching 93/3050 : Ittefaq
Fetching 94/3050 : Kick
Fetching 95/3050 : Masaan
Fetching 96/3050 : Raman Raghav 2.0
Fetching 97/3050 : Sanju
Fetching 98/3050 : Lust Stories
Fetching 99/3050 : Talaash
Fetching 100/3050 : Jism
Fetching 101/3050 : Dil To Pagal Hai
Fetching 102/3050 : Chennai Express
Fetching 103/3050 : Rang De Basanti
Fetching 104/3050 : Don 2
Fetching 105/3050 : Guru
Fetching 106/3050 : Dil Dhadakne Do
Fetching 107/3050 : Jodhaa Akbar
Fetching 108/3050 : Barfi!
Fetching 109/3050 : Bachna Ae Haseeno
Fetching 110/3050 : Love per Square Foot
Fetching 111/3050 : Wanted
Fetching 112/3050 : Ajab Prem Ki Ghazab Kahani
Fetching 113/3050 : Dil Bechara
Fetching 114/3050 : Pihu
Fetching 115/3050 : Tiger Zinda Hai
Fetching 116/3050 : Paheli
Fetching 117/3050 : Raazi
Fetching 118/3050 : Raja Hindustani
Fetching 119/3050 : Delhi Belly
Fetching 120/3050 : Faraaz
Fetching 121/3050 : Thugs of Hindostan
Fetching 122/3050 : Drishyam 2
Fetching 123/3050 : Dostana
Fetching 124/3050 : Mujhse Shaadi Karogi
Fetching 125/3050 : Bhool Bhulaiyaa
Fetching 126/3050 : Hera Pheri
Fetching 127/3050 : Yeh Jawaani Hai Deewani
Fetching 128/3050 : Jab Harry Met Sejal
Fetching 129/3050 : Uri: The Surgical Strike
Fetching 130/3050 : Ghost Stories
Fetching 131/3050 : A Wednesday!
Fetching 132/3050 : Wake Up Sid
Fetching 133/3050 : Pagglait
Fetching 134/3050 : Neerja
Fetching 135/3050 : Darlings
Fetching 136/3050 : Chhichhore
Fetching 137/3050 : Mohenjo Daro
Fetching 138/3050 : Mrs Undercover
Fetching 139/3050 : Housefull 2
Fetching 140/3050 : Cocktail
Fetching 141/3050 : Awaara
Fetching 142/3050 : Ajeeb Daastaans
Fetching 143/3050 : Pad Man
Fetching 144/3050 : Did It Happen?
Fetching 145/3050 : Satyameva Jayate
Fetching 146/3050 : 83
Fetching 147/3050 : Kapoor & Sons
Fetching 148/3050 : Water
Fetching 149/3050 : Hum Aapke Hain Koun..!
Fetching 150/3050 : Phir Hera Pheri
Fetching 151/3050 : Dil Se..
Fetching 152/3050 : 2 States
Fetching 153/3050 : De Dana Dan
Fetching 154/3050 : Partner
Fetching 155/3050 : Simmba
Fetching 156/3050 : Laal Singh Chaddha
Fetching 157/3050 : Koyla
Fetching 158/3050 : Trapped
Fetching 159/3050 : Hindi Medium
Fetching 160/3050 : Gunday
Fetching 161/3050 : Bhool Bhulaiyaa 2
Fetching 162/3050 : Guzaarish
Fetching 163/3050 : Tamasha
Fetching 164/3050 : Karthik Calling Karthik
Fetching 165/3050 : Baaghi 3
Fetching 166/3050 : Raat Akeli Hai
Fetching 167/3050 : Gunjan Saxena: The Kargil Girl
Fetching 168/3050 : Ra.One
Fetching 169/3050 : Race 2
Fetching 170/3050 : Pink
Fetching 171/3050 : Queen
Fetching 172/3050 : Prem Ratan Dhan Payo
Fetching 173/3050 : Billu
Fetching 174/3050 : Mother India
Fetching 175/3050 : Dil Chahta Hai
Fetching 176/3050 : Vicky Donor
Fetching 177/3050 : Mann
Fetching 178/3050 : Secret Superstar
Fetching 179/3050 : Margarita with a Straw
Fetching 180/3050 : Mimi
Fetching 181/3050 : Chori Chori Chupke Chupke
Fetching 182/3050 : Band Baaja Baaraat
Fetching 183/3050 : Goliyon Ki Raasleela Ram-Leela
Fetching 184/3050 : The Man Who Feels No Pain
Fetching 185/3050 : Baghban
Fetching 186/3050 : Krrish
Fetching 187/3050 : Kaabil
Fetching 188/3050 : Aashiqui 2
Fetching 189/3050 : Munna Bhai M.B.B.S.
Fetching 190/3050 : Mom
Fetching 191/3050 : Kahaani
Fetching 192/3050 : Housefull
Fetching 193/3050 : Mardaani
Fetching 194/3050 : Kai Po Che!
Fetching 195/3050 : Mrs. Serial Killer
Fetching 196/3050 : Hichki
Fetching 197/3050 : Sonu Ke Titu Ki Sweety
Fetching 198/3050 : Ready
Fetching 199/3050 : Chamatkar
Fetching 200/3050 : Kabir Singh
Fetching 201/3050 : Sarfarosh
Fetching 202/3050 : Baadshah
Fetching 203/3050 : Hum Tum
Fetching 204/3050 : Badla
Fetching 205/3050 : Hello Charlie
Fetching 206/3050 : Raanjhanaa
Fetching 207/3050 : Chalte Chalte
Fetching 208/3050 : Rangeela
Fetching 209/3050 : Hasee Toh Phasee
Fetching 210/3050 : Cirkus
Fetching 211/3050 : Lakshya
Fetching 212/3050 : Badlapur
Fetching 213/3050 : Desi Boyz
Fetching 214/3050 : Student of the Year 2
Fetching 215/3050 : Airlift
Fetching 216/3050 : Race
Fetching 217/3050 : Te3n
Fetching 218/3050 : Bareilly Ki Barfi
Fetching 219/3050 : AK vs AK
Fetching 220/3050 : Sardar Udham
Fetching 221/3050 : Half Girlfriend
Fetching 222/3050 : Josh
Fetching 223/3050 : Hum Dil De Chuke Sanam
Fetching 224/3050 : Humpty Sharma Ki Dulhania
Fetching 225/3050 : Sui Dhaaga - Made in India
Fetching 226/3050 : Chup Chup Ke
Fetching 227/3050 : ABCD 2
Fetching 228/3050 : Agneepath
Fetching 229/3050 : Rockstar
Fetching 230/3050 : Players
Fetching 231/3050 : Luck by Chance
Fetching 232/3050 : Gangs of Wasseypur - Part 2
Fetching 233/3050 : Hum Tumhare Hain Sanam
Fetching 234/3050 : Mission Majnu
Fetching 235/3050 : Ek Villain
Fetching 236/3050 : Phir Bhi Dil Hai Hindustani
Fetching 237/3050 : Udta Punjab
Fetching 238/3050 : Haider
Fetching 239/3050 : Jism 2
Fetching 240/3050 : Golmaal - Fun Unlimited
Fetching 241/3050 : Gehraiyaan
Fetching 242/3050 : Judwaa 2
Fetching 243/3050 : Runway 34
Fetching 244/3050 : Badrinath Ki Dulhania
Fetching 245/3050 : Pyaar Ka Punchnama
Fetching 246/3050 : Dybbuk
Fetching 247/3050 : Brothers
Fetching 248/3050 : Saathiya
Fetching 249/3050 : Mary Kom
Fetching 250/3050 : Jagga Jasoos
Fetching 251/3050 : Dum Laga Ke Haisha
Fetching 252/3050 : Tere Naam
Fetching 253/3050 : Sardar Ka Grandson
Fetching 254/3050 : Mr. India
Fetching 255/3050 : Chandni Chowk to China
Fetching 256/3050 : Dus
Fetching 257/3050 : Ugly
Fetching 258/3050 : Raajneeti
Fetching 259/3050 : Dabangg 2
Fetching 260/3050 : Golmaal Again
Fetching 261/3050 : Dishoom
Fetching 262/3050 : Action Replayy
Fetching 263/3050 : Pyaar Kiya To Darna Kya
Fetching 264/3050 : Koi... Mil Gaya
Fetching 265/3050 : Saawariya
Fetching 266/3050 : Super 30
Fetching 267/3050 : I Hate Luv Storys
Fetching 268/3050 : Rowdy Rathore
Fetching 269/3050 : Singham Returns
Fetching 270/3050 : No Entry
Fetching 271/3050 : R... Rajkumar
Fetching 272/3050 : Tanhaji: The Unsung Warrior
Fetching 273/3050 : Udaan
Fetching 274/3050 : Border
Fetching 275/3050 : Toilet: A Love Story
Fetching 276/3050 : Raid
Fetching 277/3050 : Badmaash Company
Fetching 278/3050 : Qala
Fetching 279/3050 : Malang
Fetching 280/3050 : Dev.D
Fetching 281/3050 : Indian
Fetching 282/3050 : The Dirty Picture
Fetching 283/3050 : Fan
Fetching 284/3050 : M.S. Dhoni: The Untold Story
Fetching 285/3050 : Shaandaar
Fetching 286/3050 : Salaam Namaste
Fetching 287/3050 : Badhaai Ho
Fetching 288/3050 : Table No. 21
Fetching 289/3050 : Company
Fetching 290/3050 : Ae Dil Hai Mushkil
Fetching 291/3050 : Shakti: The Power
Fetching 292/3050 : Masti
Fetching 293/3050 : Main Tera Hero
Fetching 294/3050 : Darr
Fetching 295/3050 : Bhoothnath
Fetching 296/3050 : Baaghi 2
Fetching 297/3050 : Talvar
Fetching 298/3050 : Hum Saath Saath Hain
Fetching 299/3050 : An Action Hero
Fetching 300/3050 : Taal
Fetching 301/3050 : Force 2
Fetching 302/3050 : ABCD
Fetching 303/3050 : New York
Fetching 304/3050 : Blackmail
Fetching 305/3050 : Golmaal 3
Fetching 306/3050 : Shershaah
Fetching 307/3050 : The Sky Is Pink
Fetching 308/3050 : Once Upon a Time in Mumbaai
Fetching 309/3050 : Tubelight
Fetching 310/3050 : Hungama
Fetching 311/3050 : Hello Brother
Fetching 312/3050 : Phone Bhoot
Fetching 313/3050 : The Kashmir Files
Fetching 314/3050 : Love Aaj Kal
Fetching 315/3050 : Thar
Fetching 316/3050 : Andaz Apna Apna
Fetching 317/3050 : Nayak: The Real Hero
Fetching 318/3050 : Gadar: Ek Prem Katha
Fetching 319/3050 : Special 26
Fetching 320/3050 : Fashion
Fetching 321/3050 : Kuttey
Fetching 322/3050 : Zanjeer
Fetching 323/3050 : Lost
Fetching 324/3050 : October
Fetching 325/3050 : Yes Boss
Fetching 326/3050 : Shivaay
Fetching 327/3050 : Attack
Fetching 328/3050 : Aaja Nachle
Fetching 329/3050 : Madras Cafe
Fetching 330/3050 : Raabta
Fetching 331/3050 : Pardes
Fetching 332/3050 : Good Newwz
Fetching 333/3050 : Anjaam
Fetching 334/3050 : Rocket Singh: Salesman of the Year
Fetching 335/3050 : Naam Shabana
Fetching 336/3050 : Ishqiya
Fetching 337/3050 : Bombay Talkies
Fetching 338/3050 : Heyy Babyy
Fetching 339/3050 : Garv: Pride and Honour
Fetching 340/3050 : Stree
Fetching 341/3050 : Tees Maar Khan
Fetching 342/3050 : Panipat
Fetching 343/3050 : Chal Mere Bhai
Fetching 344/3050 : Anjaana Anjaani
Fetching 345/3050 : Samrat Prithviraj
Fetching 346/3050 : Badhaai Do
Fetching 347/3050 : Jung
Fetching 348/3050 : Sarkar
Fetching 349/3050 : Haseen Dillruba
Fetching 350/3050 : Shubh Mangal Zyada Saavdhan
Fetching 351/3050 : Commando - A One Man Army
Fetching 352/3050 : Mera Naam Joker
Fetching 353/3050 : Ishaqzaade
Fetching 354/3050 : 7 Khoon Maaf
Fetching 355/3050 : Tanu Weds Manu: Returns
Fetching 356/3050 : Veer
Fetching 357/3050 : Article 15
Fetching 358/3050 : Mardaani 2
Fetching 359/3050 : Baby
Fetching 360/3050 : Highway
Fetching 361/3050 : The Ghazi Attack
Fetching 362/3050 : Dabangg
Fetching 363/3050 : Ram Jaane
Fetching 364/3050 : Aiyaary
Fetching 365/3050 : Hate Story 2
Fetching 366/3050 : Duplicate
Fetching 367/3050 : Joker
Fetching 368/3050 : Agneepath
Fetching 369/3050 : Paan Singh Tomar
Fetching 370/3050 : Tooth Pari: When Love Bites
Fetching 371/3050 : Manjhi: The Mountain Man
Fetching 372/3050 : Life in a Metro
Fetching 373/3050 : Rustom
Fetching 374/3050 : Gulabo Sitabo
Fetching 375/3050 : Ek Villain Returns
Fetching 376/3050 : Housefull 3
Fetching 377/3050 : Madaari
Fetching 378/3050 : Chaahat
Fetching 379/3050 : Climax
Fetching 380/3050 : No One Killed Jessica
Fetching 381/3050 : Ram Teri Ganga Maili
Fetching 382/3050 : Kalyug
Fetching 383/3050 : Parched
Fetching 384/3050 : Luck
Fetching 385/3050 : Gold
Fetching 386/3050 : Singh Is Kinng
Fetching 387/3050 : One 2 Ka 4
Fetching 388/3050 : Ta Ra Rum Pum
Fetching 389/3050 : NH10
Fetching 390/3050 : Bharat
Fetching 391/3050 : Umrao Jaan
Fetching 392/3050 : Satya
Fetching 393/3050 : Shubh Mangal Saavdhan
Fetching 394/3050 : Mission Mangal
Fetching 395/3050 : Newton
Fetching 396/3050 : Luka Chuppi
Fetching 397/3050 : Photograph
Fetching 398/3050 : Bombay Rose
Fetching 399/3050 : Jaanwar
Fetching 400/3050 : Ankahi Kahaniya
Fetching 401/3050 : Bhagam Bhag
Fetching 402/3050 : Manorama Six Feet Under
Fetching 403/3050 : Kambakkht Ishq
Fetching 404/3050 : Phantom
Fetching 405/3050 : Game
Fetching 406/3050 : Anand
Fetching 407/3050 : Namastey London
Fetching 408/3050 : Kaminey
Fetching 409/3050 : Manikarnika: The Queen of Jhansi
Fetching 410/3050 : A Thursday
Fetching 411/3050 : Bala
Fetching 412/3050 : Kabhi Haan Kabhi Naa
Fetching 413/3050 : Tevar
Fetching 414/3050 : English Babu Desi Mem
Fetching 415/3050 : Ginny Weds Sunny
Fetching 416/3050 : Sir
Fetching 417/3050 : Jolly LLB 2
Fetching 418/3050 : Vaastav
Fetching 419/3050 : Sarkar Raj
Fetching 420/3050 : Sanam Re
Fetching 421/3050 : Coolie
Fetching 422/3050 : Almost Pyaar with DJ Mohabbat
Fetching 423/3050 : The Journey of Karma
Fetching 424/3050 : Doli Saja Ke Rakhna
Fetching 425/3050 : Kill Dil
Fetching 426/3050 : Jai Ho
Fetching 427/3050 : Mission Kashmir
Fetching 428/3050 : Ki & Ka
Fetching 429/3050 : Disco Dancer
Fetching 430/3050 : That Girl in Yellow Boots
Fetching 431/3050 : Khoobsurat
Fetching 432/3050 : Omkara
Fetching 433/3050 : Son of Sardaar
Fetching 434/3050 : Dabangg 3
Fetching 435/3050 : Freddy
Fetching 436/3050 : Chef
Fetching 437/3050 : Gangster
Fetching 438/3050 : Stanley Ka Dabba
Fetching 439/3050 : Ek Ladki Ko Dekha Toh Aisa Laga
Fetching 440/3050 : Wazir
Fetching 441/3050 : Auzaar
Fetching 442/3050 : Patiala House
Fetching 443/3050 : Judwaa
Fetching 444/3050 : Aamir
Fetching 445/3050 : Lootera
Fetching 446/3050 : Tu Jhoothi Main Makkaar
Fetching 447/3050 : Shaadi Mein Zaroor Aana
Fetching 448/3050 : Bhediya
Fetching 449/3050 : Mumbai Diaries
Fetching 450/3050 : 1920 London
Fetching 451/3050 : Rocky Handsome
Fetching 452/3050 : Tanu Weds Manu
Fetching 453/3050 : Kismat Konnection
Fetching 454/3050 : Kalank
Fetching 455/3050 : Motichoor Chaknachoor
Fetching 456/3050 : Meenakshi Sundareshwar
Fetching 457/3050 : Haseena Maan Jaayegi
Fetching 458/3050 : Lipstick Under My Burkha
Fetching 459/3050 : Don
Fetching 460/3050 : Fukrey Returns
Fetching 461/3050 : Satte Pe Satta
Fetching 462/3050 : Kis Kisko Pyaar Karoon
Fetching 463/3050 : Kaal
Fetching 464/3050 : David
Fetching 465/3050 : Raksha Bandhan
Fetching 466/3050 : Khuda Haafiz
Fetching 467/3050 : Baazaar
Fetching 468/3050 : Dhan Dhana Dhan Goal
Fetching 469/3050 : Golmaal Returns
Fetching 470/3050 : Salaam-e-Ishq
Fetching 471/3050 : Jolly LLB
Fetching 472/3050 : Peepli Live
Fetching 473/3050 : Fukrey
Fetching 474/3050 : Manto
Fetching 475/3050 : Qayamat Se Qayamat Tak
Fetching 476/3050 : Ek Main Aur Ekk Tu
Fetching 477/3050 : Ek Hasina Thi
Fetching 478/3050 : Khosla Ka Ghosla!
Fetching 479/3050 : Kaali Khuhi
Fetching 480/3050 : Dulhan Hum Le Jayenge
Fetching 481/3050 : Salaam Bombay!
Fetching 482/3050 : Bell Bottom
Fetching 483/3050 : Detective Byomkesh Bakshy!
Fetching 484/3050 : LOC: Kargil
Fetching 485/3050 : Dhaakad
Fetching 486/3050 : Choked: Paisa Bolta Hai
Fetching 487/3050 : 36 China Town
Fetching 488/3050 : Go Goa Gone
Fetching 489/3050 : Eklavya: The Royal Guard
Fetching 490/3050 : Thappad
Fetching 491/3050 : Tridev
Fetching 492/3050 : Kurbaan
Fetching 493/3050 : Dasvi
Fetching 494/3050 : Aarakshan
Fetching 495/3050 : Honeymoon Travels Pvt. Ltd.
Fetching 496/3050 : Bank Chor
Fetching 497/3050 : Shaan
Fetching 498/3050 : Pati Patni Aur Woh
Fetching 499/3050 : Nagina
Fetching 500/3050 : Parmanu: The Story of Pokhran
Fetching 501/3050 : Trimurti
Fetching 502/3050 : Fitoor
Fetching 503/3050 : Chaahat
Fetching 504/3050 : Hacker 3.0
Fetching 505/3050 : Ship of Theseus
Fetching 506/3050 : Chupke Chupke
Fetching 507/3050 : Tumko Na Bhool Paayenge
Fetching 508/3050 : Class of '83
Fetching 509/3050 : Rock On!!
Fetching 510/3050 : Maharaja
Fetching 511/3050 : Welcome Back
Fetching 512/3050 : Lucky: No Time for Love
Fetching 513/3050 : Damini
Fetching 514/3050 : Double Dhamaal
Fetching 515/3050 : Tashan
Fetching 516/3050 : Lootcase
Fetching 517/3050 : Friendship
Fetching 518/3050 : Barsaat
Fetching 519/3050 : Khakee
Fetching 520/3050 : Torbaaz
Fetching 521/3050 : Mumbai Saga
Fetching 522/3050 : Maine Pyaar Kyun Kiya?
Fetching 523/3050 : Karwaan
Fetching 524/3050 : Shaitan
Fetching 525/3050 : Dil Hai Tumhaara
Fetching 526/3050 : Missing
Fetching 527/3050 : Chehre
Fetching 528/3050 : Hamari Adhuri Kahani
Fetching 529/3050 : Ishq Vishk
Fetching 530/3050 : Gurgaon
Fetching 531/3050 : Purani Haveli
Fetching 532/3050 : Amar Akbar Anthony
Fetching 533/3050 : Shamitabh
Fetching 534/3050 : Gori Tere Pyaar Mein
Fetching 535/3050 : Hello
Fetching 536/3050 : Radhe
Fetching 537/3050 : Jannat
Fetching 538/3050 : Chhapaak
Fetching 539/3050 : Jaane Bhi Do Yaaro
Fetching 540/3050 : Great Grand Masti
Fetching 541/3050 : Dhadak
Fetching 542/3050 : We Are Family
Fetching 543/3050 : The Attacks Of 26/11
Fetching 544/3050 : Holiday
Fetching 545/3050 : Aap Mujhe Achche Lagne Lage
Fetching 546/3050 : Mr. & Mrs. Khiladi
Fetching 547/3050 : Aiyyaa
Fetching 548/3050 : Ok Jaanu
Fetching 549/3050 : Page 3
Fetching 550/3050 : Naseeb
Fetching 551/3050 : Baadshaho
Fetching 552/3050 : The Unknown
Fetching 553/3050 : Murder 2
Fetching 554/3050 : Awarapan
Fetching 555/3050 : De De Pyaar De
Fetching 556/3050 : 99 Songs
Fetching 557/3050 : Race 3
Fetching 558/3050 : Zeher
Fetching 559/3050 : The Zoya Factor
Fetching 560/3050 : Gumrah
Fetching 561/3050 : Awara Paagal Deewana
Fetching 562/3050 : Mrs. Chatterjee Vs Norway
Fetching 563/3050 : Deewana Mastana
Fetching 564/3050 : Satyagraha
Fetching 565/3050 : Bbuddah Hoga Terra Baap
Fetching 566/3050 : Shiddat
Fetching 567/3050 : Serious Men
Fetching 568/3050 : A Gentleman
Fetching 569/3050 : Heropanti
Fetching 570/3050 : Oye Lucky! Lucky Oye!
Fetching 571/3050 : Agent Vinod
Fetching 572/3050 : Yaadein
Fetching 573/3050 : Padosan
Fetching 574/3050 : Marjaavaan
Fetching 575/3050 : Baabul
Fetching 576/3050 : Maine Pyar Kiya
Fetching 577/3050 : Chillar Party
Fetching 578/3050 : Lafangey Parindey
Fetching 579/3050 : Biwi No.1
Fetching 580/3050 : Total Dhamaal
Fetching 581/3050 : Dushman
Fetching 582/3050 : Murder
Fetching 583/3050 : Raja Natwarlal
Fetching 584/3050 : Sohni Mahiwal
Fetching 585/3050 : Coolie No. 1
Fetching 586/3050 : Vaah! Life Ho Toh Aisi!
Fetching 587/3050 : Hate Story IV
Fetching 588/3050 : Ekk Deewana Tha
Fetching 589/3050 : Street Dancer 3D
Fetching 590/3050 : Ek Rishtaa: The Bond of Love
Fetching 591/3050 : D-Day
Fetching 592/3050 : Mili
Fetching 593/3050 : Intercourse
Fetching 594/3050 : Sirf Tum
Fetching 595/3050 : Chandni Bar
Fetching 596/3050 : Laxmii
Fetching 597/3050 : Chhalaang
Fetching 598/3050 : Shanghai
Fetching 599/3050 : Rehnaa Hai Terre Dil Mein
Fetching 600/3050 : Malamaal Weekly
Fetching 601/3050 : Tribhanga
Fetching 602/3050 : Kyon Ki...
Fetching 603/3050 : Bheed
Fetching 604/3050 : Chachi 420
Fetching 605/3050 : Masoom
Fetching 606/3050 : Yeh Dillagi
Fetching 607/3050 : Section 375
Fetching 608/3050 : Jazbaa
Fetching 609/3050 : Housefull 4
Fetching 610/3050 : Angrezi Medium
Fetching 611/3050 : Run
Fetching 612/3050 : Nasha
Fetching 613/3050 : Batla House
Fetching 614/3050 : Gharwali Baharwali
Fetching 615/3050 : Mohra

In [369]:
df=df.drop(['Unnamed: 0', 'index'],axis=1)

In [370]:
# 🔹 NEW columns for platforms
df["netflix_link"] = None
df["prime_link"] = None

In [373]:
for i, row in df.iterrows():
    print(f"Fetching {i+1}/{len(df)} : {row['title']}")
    # 🔹 ADD PLATFORM LINKS (search links)
    title_encoded = row["title"].replace(" ", "%20")
    df.at[i, "netflix_link"] = f"https://www.netflix.com/search?q={title_encoded}"
    df.at[i, "prime_link"] = f"https://www.primevideo.com/search/ref=atv_nb_sr?phrase={title_encoded}"

 


# 🔹 save new file
# df.to_csv("new_df_enriched.csv", index=False)

print("✅ Done. Saved as new_df_enriched.csv")

Fetching 1/3050 : Looop Lapeta
Fetching 2/3050 : Sooryavanshi
Fetching 3/3050 : Pathaan
Fetching 4/3050 : Chor Nikal Ke Bhaga
Fetching 5/3050 : 3 Idiots
Fetching 6/3050 : My Name Is Khan
Fetching 7/3050 : Dilwale Dulhania Le Jayenge
Fetching 8/3050 : Dhamaka
Fetching 9/3050 : Brahmāstra Part One: Shiva
Fetching 10/3050 : Andhadhun
Fetching 11/3050 : Om Shanti Om
Fetching 12/3050 : Blood Money
Fetching 13/3050 : Kabhi Khushi Kabhie Gham
Fetching 14/3050 : Dhoom 3
Fetching 15/3050 : Gumraah
Fetching 16/3050 : Dangal
Fetching 17/3050 : Kites
Fetching 18/3050 : Commando 2 -  The Black Money Trail
Fetching 19/3050 : Kabhi Alvida Naa Kehna
Fetching 20/3050 : Like Stars on Earth
Fetching 21/3050 : Drive
Fetching 22/3050 : Kuch Kuch Hota Hai
Fetching 23/3050 : Bodyguard
Fetching 24/3050 : Junglee
Fetching 25/3050 : The Girl on the Train
Fetching 26/3050 : Baaghi
Fetching 27/3050 : Student of the Year
Fetching 28/3050 : Karan Arjun
Fetching 29/3050 : Gangs of Wasseypur - Part 1
Fetching 30/3050 : Raees
Fetching 31/3050 : Bajrangi Bhaijaan
Fetching 32/3050 : PK
Fetching 33/3050 : Rab Ne Bana Di Jodi
Fetching 34/3050 : Dhoom 2
Fetching 35/3050 : Padmaavat
Fetching 36/3050 : Mohabbatein
Fetching 37/3050 : Mujhse Dosti Karoge!
Fetching 38/3050 : Monica, O My Darling
Fetching 39/3050 : Veer-Zaara
Fetching 40/3050 : Bang Bang!
Fetching 41/3050 : Lagaan: Once Upon a Time in India
Fetching 42/3050 : The Lunchbox
Fetching 43/3050 : Gangubai Kathiawadi
Fetching 44/3050 : Monsoon Wedding
Fetching 45/3050 : Zindagi Na Milegi Dobara
Fetching 46/3050 : Swades
Fetching 47/3050 : Dilwale
Fetching 48/3050 : Ghajini
Fetching 49/3050 : Bhaag Milkha Bhaag
Fetching 50/3050 : Jab Tak Hai Jaan
Fetching 51/3050 : Jersey
Fetching 52/3050 : Gol Maal
Fetching 53/3050 : Devdas
Fetching 54/3050 : Ludo
Fetching 55/3050 : Gaslight
Fetching 56/3050 : Ek Tha Tiger
Fetching 57/3050 : Chak De! India
Fetching 58/3050 : English Vinglish
Fetching 59/3050 : War
Fetching 60/3050 : Bholaa
Fetching 61/3050 : Vivah
Fetching 62/3050 : Gully Boy
Fetching 63/3050 : Kal Ho Naa Ho
Fetching 64/3050 : Dear Zindagi
Fetching 65/3050 : Aśoka
Fetching 66/3050 : Singham
Fetching 67/3050 : Welcome
Fetching 68/3050 : Fanaa
Fetching 69/3050 : Main Hoon Na
Fetching 70/3050 : Sholay
Fetching 71/3050 : Guilty
Fetching 72/3050 : Black
Fetching 73/3050 : Dhoom
Fetching 74/3050 : Kesari
Fetching 75/3050 : Happy New Year
Fetching 76/3050 : Sanam Teri Kasam
Fetching 77/3050 : Sultan
Fetching 78/3050 : Piku
Fetching 79/3050 : Krrish 3
Fetching 80/3050 : Tumbbad
Fetching 81/3050 : Zero
Fetching 82/3050 : Black Friday
Fetching 83/3050 : Don
Fetching 84/3050 : Jab We Met
Fetching 85/3050 : Aladin
Fetching 86/3050 : Jaadugar
Fetching 87/3050 : Kaho Naa... Pyaar Hai
Fetching 88/3050 : B.A. Pass
Fetching 89/3050 : OMG: Oh My God!
Fetching 90/3050 : Bajirao Mastani
Fetching 91/3050 : Drishyam
Fetching 92/3050 : Baazigar
Fetching 93/3050 : Ittefaq
Fetching 94/3050 : Kick
Fetching 95/3050 : Masaan
Fetching 96/3050 : Raman Raghav 2.0
Fetching 97/3050 : Sanju
Fetching 98/3050 : Lust Stories
Fetching 99/3050 : Talaash
Fetching 100/3050 : Jism
Fetching 101/3050 : Dil To Pagal Hai
Fetching 102/3050 : Chennai Express
Fetching 103/3050 : Rang De Basanti
Fetching 104/3050 : Don 2
Fetching 105/3050 : Guru
Fetching 106/3050 : Dil Dhadakne Do
Fetching 107/3050 : Jodhaa Akbar
Fetching 108/3050 : Barfi!
Fetching 109/3050 : Bachna Ae Haseeno
Fetching 110/3050 : Love per Square Foot
Fetching 111/3050 : Wanted
Fetching 112/3050 : Ajab Prem Ki Ghazab Kahani
Fetching 113/3050 : Dil Bechara
Fetching 114/3050 : Pihu
Fetching 115/3050 : Tiger Zinda Hai
Fetching 116/3050 : Paheli
Fetching 117/3050 : Raazi
Fetching 118/3050 : Raja Hindustani
Fetching 119/3050 : Delhi Belly
Fetching 120/3050 : Faraaz
Fetching 121/3050 : Thugs of Hindostan
Fetching 122/3050 : Drishyam 2
Fetching 123/3050 : Dostana
Fetching 124/3050 : Mujhse Shaadi Karogi
Fetching 125/3050 : Bhool Bhulaiyaa
Fetching 126/3050 : Hera Pheri
Fetching 127/3050 : Yeh Jawaani Hai Deewani
Fetching 128/3050 : Jab Harry Met Sejal
Fetching 129/3050 : Uri: The Surgical Strike
Fetching 130/3050 : Ghost Stories
Fetching 131/3050 : A Wednesday!
Fetching 132/3050 : Wake Up Sid
Fetching 133/3050 : Pagglait
Fetching 134/3050 : Neerja
Fetching 135/3050 : Darlings
Fetching 136/3050 : Chhichhore
Fetching 137/3050 : Mohenjo Daro
Fetching 138/3050 : Mrs Undercover
Fetching 139/3050 : Housefull 2
Fetching 140/3050 : Cocktail
Fetching 141/3050 : Awaara
Fetching 142/3050 : Ajeeb Daastaans
Fetching 143/3050 : Pad Man
Fetching 144/3050 : Did It Happen?
Fetching 145/3050 : Satyameva Jayate
Fetching 146/3050 : 83
Fetching 147/3050 : Kapoor & Sons
Fetching 148/3050 : Water
Fetching 149/3050 : Hum Aapke Hain Koun..!
Fetching 150/3050 : Phir Hera Pheri
Fetching 151/3050 : Dil Se..
Fetching 152/3050 : 2 States
Fetching 153/3050 : De Dana Dan
Fetching 154/3050 : Partner
Fetching 155/3050 : Simmba
Fetching 156/3050 : Laal Singh Chaddha
Fetching 157/3050 : Koyla
Fetching 158/3050 : Trapped
Fetching 159/3050 : Hindi Medium
Fetching 160/3050 : Gunday
Fetching 161/3050 : Bhool Bhulaiyaa 2
Fetching 162/3050 : Guzaarish
Fetching 163/3050 : Tamasha
Fetching 164/3050 : Karthik Calling Karthik
Fetching 165/3050 : Baaghi 3
Fetching 166/3050 : Raat Akeli Hai
Fetching 167/3050 : Gunjan Saxena: The Kargil Girl
Fetching 168/3050 : Ra.One
Fetching 169/3050 : Race 2
Fetching 170/3050 : Pink
Fetching 171/3050 : Queen
Fetching 172/3050 : Prem Ratan Dhan Payo
Fetching 173/3050 : Billu
Fetching 174/3050 : Mother India
Fetching 175/3050 : Dil Chahta Hai
Fetching 176/3050 : Vicky Donor
Fetching 177/3050 : Mann
Fetching 178/3050 : Secret Superstar
Fetching 179/3050 : Margarita with a Straw
Fetching 180/3050 : Mimi
Fetching 181/3050 : Chori Chori Chupke Chupke
Fetching 182/3050 : Band Baaja Baaraat
Fetching 183/3050 : Goliyon Ki Raasleela Ram-Leela
Fetching 184/3050 : The Man Who Feels No Pain
Fetching 185/3050 : Baghban
Fetching 186/3050 : Krrish
Fetching 187/3050 : Kaabil
Fetching 188/3050 : Aashiqui 2
Fetching 189/3050 : Munna Bhai M.B.B.S.
Fetching 190/3050 : Mom
Fetching 191/3050 : Kahaani
Fetching 192/3050 : Housefull
Fetching 193/3050 : Mardaani
Fetching 194/3050 : Kai Po Che!
Fetching 195/3050 : Mrs. Serial Killer
Fetching 196/3050 : Hichki
Fetching 197/3050 : Sonu Ke Titu Ki Sweety
Fetching 198/3050 : Ready
Fetching 199/3050 : Chamatkar
Fetching 200/3050 : Kabir Singh
Fetching 201/3050 : Sarfarosh
Fetching 202/3050 : Baadshah
Fetching 203/3050 : Hum Tum
Fetching 204/3050 : Badla
Fetching 205/3050 : Hello Charlie
Fetching 206/3050 : Raanjhanaa
Fetching 207/3050 : Chalte Chalte
Fetching 208/3050 : Rangeela
Fetching 209/3050 : Hasee Toh Phasee
Fetching 210/3050 : Cirkus
Fetching 211/3050 : Lakshya
Fetching 212/3050 : Badlapur
Fetching 213/3050 : Desi Boyz
Fetching 214/3050 : Student of the Year 2
Fetching 215/3050 : Airlift
Fetching 216/3050 : Race
Fetching 217/3050 : Te3n
Fetching 218/3050 : Bareilly Ki Barfi
Fetching 219/3050 : AK vs AK
Fetching 220/3050 : Sardar Udham
Fetching 221/3050 : Half Girlfriend
Fetching 222/3050 : Josh
Fetching 223/3050 : Hum Dil De Chuke Sanam
Fetching 224/3050 : Humpty Sharma Ki Dulhania
Fetching 225/3050 : Sui Dhaaga - Made in India
Fetching 226/3050 : Chup Chup Ke
Fetching 227/3050 : ABCD 2
Fetching 228/3050 : Agneepath
Fetching 229/3050 : Rockstar
Fetching 230/3050 : Players
Fetching 231/3050 : Luck by Chance
Fetching 232/3050 : Gangs of Wasseypur - Part 2
Fetching 233/3050 : Hum Tumhare Hain Sanam
Fetching 234/3050 : Mission Majnu
Fetching 235/3050 : Ek Villain
Fetching 236/3050 : Phir Bhi Dil Hai Hindustani
Fetching 237/3050 : Udta Punjab
Fetching 238/3050 : Haider
Fetching 239/3050 : Jism 2
Fetching 240/3050 : Golmaal - Fun Unlimited
Fetching 241/3050 : Gehraiyaan
Fetching 242/3050 : Judwaa 2
Fetching 243/3050 : Runway 34
Fetching 244/3050 : Badrinath Ki Dulhania
Fetching 245/3050 : Pyaar Ka Punchnama
Fetching 246/3050 : Dybbuk
Fetching 247/3050 : Brothers
Fetching 248/3050 : Saathiya
Fetching 249/3050 : Mary Kom
Fetching 250/3050 : Jagga Jasoos
Fetching 251/3050 : Dum Laga Ke Haisha
Fetching 252/3050 : Tere Naam
Fetching 253/3050 : Sardar Ka Grandson
Fetching 254/3050 : Mr. India
Fetching 255/3050 : Chandni Chowk to China
Fetching 256/3050 : Dus
Fetching 257/3050 : Ugly
Fetching 258/3050 : Raajneeti
Fetching 259/3050 : Dabangg 2
Fetching 260/3050 : Golmaal Again
Fetching 261/3050 : Dishoom
Fetching 262/3050 : Action Replayy
Fetching 263/3050 : Pyaar Kiya To Darna Kya
Fetching 264/3050 : Koi... Mil Gaya
Fetching 265/3050 : Saawariya
Fetching 266/3050 : Super 30
Fetching 267/3050 : I Hate Luv Storys
Fetching 268/3050 : Rowdy Rathore
Fetching 269/3050 : Singham Returns
Fetching 270/3050 : No Entry
Fetching 271/3050 : R... Rajkumar
Fetching 272/3050 : Tanhaji: The Unsung Warrior
Fetching 273/3050 : Udaan
Fetching 274/3050 : Border
Fetching 275/3050 : Toilet: A Love Story
Fetching 276/3050 : Raid
Fetching 277/3050 : Badmaash Company
Fetching 278/3050 : Qala
Fetching 279/3050 : Malang
Fetching 280/3050 : Dev.D
Fetching 281/3050 : Indian
Fetching 282/3050 : The Dirty Picture
Fetching 283/3050 : Fan
Fetching 284/3050 : M.S. Dhoni: The Untold Story
Fetching 285/3050 : Shaandaar
Fetching 286/3050 : Salaam Namaste
Fetching 287/3050 : Badhaai Ho
Fetching 288/3050 : Table No. 21
Fetching 289/3050 : Company
Fetching 290/3050 : Ae Dil Hai Mushkil
Fetching 291/3050 : Shakti: The Power
Fetching 292/3050 : Masti
Fetching 293/3050 : Main Tera Hero
Fetching 294/3050 : Darr
Fetching 295/3050 : Bhoothnath
Fetching 296/3050 : Baaghi 2
Fetching 297/3050 : Talvar
Fetching 298/3050 : Hum Saath Saath Hain
Fetching 299/3050 : An Action Hero
Fetching 300/3050 : Taal
Fetching 301/3050 : Force 2
Fetching 302/3050 : ABCD
Fetching 303/3050 : New York
Fetching 304/3050 : Blackmail
Fetching 305/3050 : Golmaal 3
Fetching 306/3050 : Shershaah
Fetching 307/3050 : The Sky Is Pink
Fetching 308/3050 : Once Upon a Time in Mumbaai
Fetching 309/3050 : Tubelight
Fetching 310/3050 : Hungama
Fetching 311/3050 : Hello Brother
Fetching 312/3050 : Phone Bhoot
Fetching 313/3050 : The Kashmir Files
Fetching 314/3050 : Love Aaj Kal
Fetching 315/3050 : Thar
Fetching 316/3050 : Andaz Apna Apna
Fetching 317/3050 : Nayak: The Real Hero
Fetching 318/3050 : Gadar: Ek Prem Katha
Fetching 319/3050 : Special 26
Fetching 320/3050 : Fashion
Fetching 321/3050 : Kuttey
Fetching 322/3050 : Zanjeer
Fetching 323/3050 : Lost
Fetching 324/3050 : October
Fetching 325/3050 : Yes Boss
Fetching 326/3050 : Shivaay
Fetching 327/3050 : Attack
Fetching 328/3050 : Aaja Nachle
Fetching 329/3050 : Madras Cafe
Fetching 330/3050 : Raabta
Fetching 331/3050 : Pardes
Fetching 332/3050 : Good Newwz
Fetching 333/3050 : Anjaam
Fetching 334/3050 : Rocket Singh: Salesman of the Year
Fetching 335/3050 : Naam Shabana
Fetching 336/3050 : Ishqiya
Fetching 337/3050 : Bombay Talkies
Fetching 338/3050 : Heyy Babyy
Fetching 339/3050 : Garv: Pride and Honour
Fetching 340/3050 : Stree
Fetching 341/3050 : Tees Maar Khan
Fetching 342/3050 : Panipat
Fetching 343/3050 : Chal Mere Bhai
Fetching 344/3050 : Anjaana Anjaani
Fetching 345/3050 : Samrat Prithviraj
Fetching 346/3050 : Badhaai Do
Fetching 347/3050 : Jung
Fetching 348/3050 : Sarkar
Fetching 349/3050 : Haseen Dillruba
Fetching 350/3050 : Shubh Mangal Zyada Saavdhan
Fetching 351/3050 : Commando - A One Man Army
Fetching 352/3050 : Mera Naam Joker
Fetching 353/3050 : Ishaqzaade
Fetching 354/3050 : 7 Khoon Maaf
Fetching 355/3050 : Tanu Weds Manu: Returns
Fetching 356/3050 : Veer
Fetching 357/3050 : Article 15
Fetching 358/3050 : Mardaani 2
Fetching 359/3050 : Baby
Fetching 360/3050 : Highway
Fetching 361/3050 : The Ghazi Attack
Fetching 362/3050 : Dabangg
Fetching 363/3050 : Ram Jaane
Fetching 364/3050 : Aiyaary
Fetching 365/3050 : Hate Story 2
Fetching 366/3050 : Duplicate
Fetching 367/3050 : Joker
Fetching 368/3050 : Agneepath
Fetching 369/3050 : Paan Singh Tomar
Fetching 370/3050 : Tooth Pari: When Love Bites
Fetching 371/3050 : Manjhi: The Mountain Man
Fetching 372/3050 : Life in a Metro
Fetching 373/3050 : Rustom
Fetching 374/3050 : Gulabo Sitabo
Fetching 375/3050 : Ek Villain Returns
Fetching 376/3050 : Housefull 3
Fetching 377/3050 : Madaari
Fetching 378/3050 : Chaahat
Fetching 379/3050 : Climax
Fetching 380/3050 : No One Killed Jessica
Fetching 381/3050 : Ram Teri Ganga Maili
Fetching 382/3050 : Kalyug
Fetching 383/3050 : Parched
Fetching 384/3050 : Luck
Fetching 385/3050 : Gold
Fetching 386/3050 : Singh Is Kinng
Fetching 387/3050 : One 2 Ka 4
Fetching 388/3050 : Ta Ra Rum Pum
Fetching 389/3050 : NH10
Fetching 390/3050 : Bharat
Fetching 391/3050 : Umrao Jaan
Fetching 392/3050 : Satya
Fetching 393/3050 : Shubh Mangal Saavdhan
Fetching 394/3050 : Mission Mangal
Fetching 395/3050 : Newton
Fetching 396/3050 : Luka Chuppi
Fetching 397/3050 : Photograph
Fetching 398/3050 : Bombay Rose
Fetching 399/3050 : Jaanwar
Fetching 400/3050 : Ankahi Kahaniya
Fetching 401/3050 : Bhagam Bhag
Fetching 402/3050 : Manorama Six Feet Under
Fetching 403/3050 : Kambakkht Ishq
Fetching 404/3050 : Phantom
Fetching 405/3050 : Game
Fetching 406/3050 : Anand
Fetching 407/3050 : Namastey London
Fetching 408/3050 : Kaminey
Fetching 409/3050 : Manikarnika: The Queen of Jhansi
Fetching 410/3050 : A Thursday
Fetching 411/3050 : Bala
Fetching 412/3050 : Kabhi Haan Kabhi Naa
Fetching 413/3050 : Tevar
Fetching 414/3050 : English Babu Desi Mem
Fetching 415/3050 : Ginny Weds Sunny
Fetching 416/3050 : Sir
Fetching 417/3050 : Jolly LLB 2
Fetching 418/3050 : Vaastav
Fetching 419/3050 : Sarkar Raj
Fetching 420/3050 : Sanam Re
Fetching 421/3050 : Coolie
Fetching 422/3050 : Almost Pyaar with DJ Mohabbat
Fetching 423/3050 : The Journey of Karma
Fetching 424/3050 : Doli Saja Ke Rakhna
Fetching 425/3050 : Kill Dil
Fetching 426/3050 : Jai Ho
Fetching 427/3050 : Mission Kashmir
Fetching 428/3050 : Ki & Ka
Fetching 429/3050 : Disco Dancer
Fetching 430/3050 : That Girl in Yellow Boots
Fetching 431/3050 : Khoobsurat
Fetching 432/3050 : Omkara
Fetching 433/3050 : Son of Sardaar
Fetching 434/3050 : Dabangg 3
Fetching 435/3050 : Freddy
Fetching 436/3050 : Chef
Fetching 437/3050 : Gangster
Fetching 438/3050 : Stanley Ka Dabba
Fetching 439/3050 : Ek Ladki Ko Dekha Toh Aisa Laga
Fetching 440/3050 : Wazir
Fetching 441/3050 : Auzaar
Fetching 442/3050 : Patiala House
Fetching 443/3050 : Judwaa
Fetching 444/3050 : Aamir
Fetching 445/3050 : Lootera
Fetching 446/3050 : Tu Jhoothi Main Makkaar
Fetching 447/3050 : Shaadi Mein Zaroor Aana
Fetching 448/3050 : Bhediya
Fetching 449/3050 : Mumbai Diaries
Fetching 450/3050 : 1920 London
Fetching 451/3050 : Rocky Handsome
Fetching 452/3050 : Tanu Weds Manu
Fetching 453/3050 : Kismat Konnection
Fetching 454/3050 : Kalank
Fetching 455/3050 : Motichoor Chaknachoor
Fetching 456/3050 : Meenakshi Sundareshwar
Fetching 457/3050 : Haseena Maan Jaayegi
Fetching 458/3050 : Lipstick Under My Burkha
Fetching 459/3050 : Don
Fetching 460/3050 : Fukrey Returns
Fetching 461/3050 : Satte Pe Satta
Fetching 462/3050 : Kis Kisko Pyaar Karoon
Fetching 463/3050 : Kaal
Fetching 464/3050 : David
Fetching 465/3050 : Raksha Bandhan
Fetching 466/3050 : Khuda Haafiz
Fetching 467/3050 : Baazaar
Fetching 468/3050 : Dhan Dhana Dhan Goal
Fetching 469/3050 : Golmaal Returns
Fetching 470/3050 : Salaam-e-Ishq
Fetching 471/3050 : Jolly LLB
Fetching 472/3050 : Peepli Live
Fetching 473/3050 : Fukrey
Fetching 474/3050 : Manto
Fetching 475/3050 : Qayamat Se Qayamat Tak
Fetching 476/3050 : Ek Main Aur Ekk Tu
Fetching 477/3050 : Ek Hasina Thi
Fetching 478/3050 : Khosla Ka Ghosla!
Fetching 479/3050 : Kaali Khuhi
Fetching 480/3050 : Dulhan Hum Le Jayenge
Fetching 481/3050 : Salaam Bombay!
Fetching 482/3050 : Bell Bottom
Fetching 483/3050 : Detective Byomkesh Bakshy!
Fetching 484/3050 : LOC: Kargil
Fetching 485/3050 : Dhaakad
Fetching 486/3050 : Choked: Paisa Bolta Hai
Fetching 487/3050 : 36 China Town
Fetching 488/3050 : Go Goa Gone
Fetching 489/3050 : Eklavya: The Royal Guard
Fetching 490/3050 : Thappad
Fetching 491/3050 : Tridev
Fetching 492/3050 : Kurbaan
Fetching 493/3050 : Dasvi
Fetching 494/3050 : Aarakshan
Fetching 495/3050 : Honeymoon Travels Pvt. Ltd.
Fetching 496/3050 : Bank Chor
Fetching 497/3050 : Shaan
Fetching 498/3050 : Pati Patni Aur Woh
Fetching 499/3050 : Nagina
Fetching 500/3050 : Parmanu: The Story of Pokhran
Fetching 501/3050 : Trimurti
Fetching 502/3050 : Fitoor
Fetching 503/3050 : Chaahat
Fetching 504/3050 : Hacker 3.0
Fetching 505/3050 : Ship of Theseus
Fetching 506/3050 : Chupke Chupke
Fetching 507/3050 : Tumko Na Bhool Paayenge
Fetching 508/3050 : Class of '83
Fetching 509/3050 : Rock On!!
Fetching 510/3050 : Maharaja
Fetching 511/3050 : Welcome Back
Fetching 512/3050 : Lucky: No Time for Love
Fetching 513/3050 : Damini
Fetching 514/3050 : Double Dhamaal
Fetching 515/3050 : Tashan
Fetching 516/3050 : Lootcase
Fetching 517/3050 : Friendship
Fetching 518/3050 : Barsaat
Fetching 519/3050 : Khakee
Fetching 520/3050 : Torbaaz
Fetching 521/3050 : Mumbai Saga
Fetching 522/3050 : Maine Pyaar Kyun Kiya?
Fetching 523/3050 : Karwaan
Fetching 524/3050 : Shaitan
Fetching 525/3050 : Dil Hai Tumhaara
Fetching 526/3050 : Missing
Fetching 527/3050 : Chehre
Fetching 528/3050 : Hamari Adhuri Kahani
Fetching 529/3050 : Ishq Vishk
Fetching 530/3050 : Gurgaon
Fetching 531/3050 : Purani Haveli
Fetching 532/3050 : Amar Akbar Anthony
Fetching 533/3050 : Shamitabh
Fetching 534/3050 : Gori Tere Pyaar Mein
Fetching 535/3050 : Hello
Fetching 536/3050 : Radhe
Fetching 537/3050 : Jannat
Fetching 538/3050 : Chhapaak
Fetching 539/3050 : Jaane Bhi Do Yaaro
Fetching 540/3050 : Great Grand Masti
Fetching 541/3050 : Dhadak
Fetching 542/3050 : We Are Family
Fetching 543/3050 : The Attacks Of 26/11
Fetching 544/3050 : Holiday
Fetching 545/3050 : Aap Mujhe Achche Lagne Lage
Fetching 546/3050 : Mr. & Mrs. Khiladi
Fetching 547/3050 : Aiyyaa
Fetching 548/3050 : Ok Jaanu
Fetching 549/3050 : Page 3
Fetching 550/3050 : Naseeb
Fetching 551/3050 : Baadshaho
Fetching 552/3050 : The Unknown
Fetching 553/3050 : Murder 2
Fetching 554/3050 : Awarapan
Fetching 555/3050 : De De Pyaar De
Fetching 556/3050 : 99 Songs
Fetching 557/3050 : Race 3
Fetching 558/3050 : Zeher
Fetching 559/3050 : The Zoya Factor
Fetching 560/3050 : Gumrah
Fetching 561/3050 : Awara Paagal Deewana
Fetching 562/3050 : Mrs. Chatterjee Vs Norway
Fetching 563/3050 : Deewana Mastana
Fetching 564/3050 : Satyagraha
Fetching 565/3050 : Bbuddah Hoga Terra Baap
Fetching 566/3050 : Shiddat
Fetching 567/3050 : Serious Men
Fetching 568/3050 : A Gentleman
Fetching 569/3050 : Heropanti
Fetching 570/3050 : Oye Lucky! Lucky Oye!
Fetching 571/3050 : Agent Vinod
Fetching 572/3050 : Yaadein
Fetching 573/3050 : Padosan
Fetching 574/3050 : Marjaavaan
Fetching 575/3050 : Baabul
Fetching 576/3050 : Maine Pyar Kiya
Fetching 577/3050 : Chillar Party
Fetching 578/3050 : Lafangey Parindey
Fetching 579/3050 : Biwi No.1
Fetching 580/3050 : Total Dhamaal
Fetching 581/3050 : Dushman
Fetching 582/3050 : Murder
Fetching 583/3050 : Raja Natwarlal
Fetching 584/3050 : Sohni Mahiwal
Fetching 585/3050 : Coolie No. 1
Fetching 586/3050 : Vaah! Life Ho Toh Aisi!
Fetching 587/3050 : Hate Story IV
Fetching 588/3050 : Ekk Deewana Tha
Fetching 589/3050 : Street Dancer 3D
Fetching 590/3050 : Ek Rishtaa: The Bond of Love
Fetching 591/3050 : D-Day
Fetching 592/3050 : Mili
Fetching 593/3050 : Intercourse
Fetching 594/3050 : Sirf Tum
Fetching 595/3050 : Chandni Bar
Fetching 596/3050 : Laxmii
Fetching 597/3050 : Chhalaang
Fetching 598/3050 : Shanghai
Fetching 599/3050 : Rehnaa Hai Terre Dil Mein
Fetching 600/3050 : Malamaal Weekly
Fetching 601/3050 : Tribhanga
Fetching 602/3050 : Kyon Ki...
Fetching 603/3050 : Bheed
Fetching 604/3050 : Chachi 420
Fetching 605/3050 : Masoom
Fetching 606/3050 : Yeh Dillagi
Fetching 607/3050 : Section 375
Fetching 608/3050 : Jazbaa
Fetching 609/3050 : Housefull 4
Fetching 610/3050 : Angrezi Medium
Fetching 611/3050 : Run
Fetching 612/3050 : Nasha
Fetching 613/3050 : Batla House
Fetching 614/3050 : Gharwali Baharwali
Fetching 615/3050 : Mohra

In [374]:
df.head()

,movie_id,title,tags,poster,overview,release,netflix_link,prime_link
0,783461,Looop Lapeta,boyfriend lose mobsters cash savi race clock s...,https://image.tmdb.org/t/p/w342/onGdT8sYi89drv...,"When her boyfriend loses a mobster's cash, Sav...",2022-02-04,https://www.netflix.com/search?q=Looop%20Lapeta,https://www.primevideo.com/search/ref=atv_nb_s...
1,592508,Sooryavanshi,fearless faithful albeit slightly forgetful mu...,https://image.tmdb.org/t/p/w342/zgEc1Tn4iKvttP...,"A fearless, faithful albeit slightly forgetful...",2021-11-05,https://www.netflix.com/search?q=Sooryavanshi,https://www.primevideo.com/search/ref=atv_nb_s...
2,864692,Pathaan,soldier catch enemies presume dead come back c...,https://image.tmdb.org/t/p/w342/arf00BkwvXo0CF...,A soldier caught by enemies and presumed dead ...,2023-01-25,https://www.netflix.com/search?q=Pathaan,https://www.primevideo.com/search/ref=atv_nb_s...
3,1018228,Chor Nikal Ke Bhaga,flight attendant boyfriend must steal cache di...,https://image.tmdb.org/t/p/w342/1MIDERaEUMw1rY...,A flight attendant and her boyfriend must stea...,2023-03-24,https://www.netflix.com/search?q=Chor%20Nikal%...,https://www.primevideo.com/search/ref=atv_nb_s...
4,20453,3 Idiots,rascal joker dreamer genius youve never meet c...,https://image.tmdb.org/t/p/w342/66A9MqXOyVFCss...,Rascal. Joker. Dreamer. Genius... You've never...,2009-12-23,https://www.netflix.com/search?q=3%20Idiots,https://www.primevideo.com/search/ref=atv_nb_s...

In [ ]:
df["netflix_link"] = None
df["prime_link"] = None

for i, row in df.iterrows():
    movie_id = row["movie_id"]
    url = f"https://api.themoviedb.org/3/movie/{movie_id}/watch/providers?api_key={API_KEY}"
    res = requests.get(url).json()

    if "results" in res and "IN" in res["results"]:
        providers = res["results"]["IN"]
        if "flatrate" in providers:
            for p in providers["flatrate"]:
                if p["provider_name"] == "Netflix":
                    df.at[i, "netflix_link"] = providers["link"]
                if p["provider_name"] == "Amazon Prime Video":
                    df.at[i, "prime_link"] = providers["link"]

    time.sleep(0.2)